### ISSUE TITLE
[enhancement] an option to move views and lang files to custom folder

### ISSUE THREAD

**Issue by Yahav** [josiasmontag/laravel-email-verification#10]
Is it possible to move the views and language files (after published) outside the vendor folders created?
for instance, i'd like to move the view file to the views/auth folder and the language files to: lang/$LANG/emailverification.php

is this possible?

**Comment by josiasmontag** [comment]
It is Laravel convention to publish package views in the `views/vendor` folder. Would not make sense to it differently here.
However, you could just replace the published vendor blade templates with something like `@include('my.path.to.something')` to use your custom paths.

**Comment by Yahav** [comment]
and how about the language file?
also, how would i do what you suggested?
