### ISSUE TITLE
Class 'Lunaweb\User\Http\Controllers\Controller' not found

### ISSUE THREAD

**Issue by ZapevalovAnton** [josiasmontag/laravel-email-verification#2]
Laravel 5.5

In your **readme.md** file you override default Controller to custom Lunaweb\User\Http\Controllers\Controller in file RegisterController.php. Why? 
```php
use Lunaweb\EmailVerification\Traits\VerifiesEmail;
use Lunaweb\User\Http\Controllers\Controller;

class RegisterController extends Controller
{

    use RegistersUsers, VerifiesEmail;


    public function __construct()
    {
          $this->middleware('guest', ['except' => ['verify', 'showResendVerificationEmailForm', 'resendVerificationEmail']]);
          $this->middleware('auth', ['only' => ['showResendVerificationEmailForm', 'resendVerificationEmail']]);
    }

    // ...

}
```
And that Controller not found)))

![image](https://user-images.githubusercontent.com/6674242/31611760-c4c54e54-b296-11e7-98a7-e382ce1ea39b.png)

**Comment by josiasmontag** [comment]
No need to override Controller. This was an error in the RADME.
Fixed - thanks!
