### ISSUE TITLE
Route register/verify/resend not working

### ISSUE THREAD

**Issue by ZapevalovAnton** [josiasmontag/laravel-email-verification#3]
Route **register/verify/resend** redirects not verified user to **/home** page.

**Comment by josiasmontag** [comment]
It actually uses the default Laravel behaviour of the RegisterController.
See here how to customize it: https://laravel.com/docs/5.5/authentication#included-authenticating

**Comment by ZapevalovAnton** [comment]
Probably you need to add to the **readme.md** information about that need to add the showResendVerificationEmailForm method to the RegisterController.php???

**Comment by josiasmontag** [comment]
This method is part of the `VerifiesEmail` trait and the README tells to add it to the RegisterController.

**Comment by ZapevalovAnton** [comment]
And why then happens a redirect?

**Comment by josiasmontag** [comment]
The form is only shown if you are not verified. Most probably your account is already verified.

**Comment by ZapevalovAnton** [comment]
No

**Comment by ZapevalovAnton** [comment]
![image](https://user-images.githubusercontent.com/6674242/31612647-d239a3ca-b299-11e7-89aa-60a46b3dc882.png)

**Comment by ZapevalovAnton** [comment]
You can test this on https://next.tuhub.ru/register

**Comment by ZapevalovAnton** [comment]
Any ideas?

**Comment by ZapevalovAnton** [comment]
@josiasmontag What do you think?
